### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Damian0001** [Damian0001/Scouting-App#34]
- [ ] Make currently offline notice work again
- [ ] Remove all reused code and move it to somewhere like app.vue etc
- [ ] Instead of having db content just pop in use a google like spinning loading thing to disguise load time
