### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ThatOneGuyFromThatOneShow** [Damian0001/Scouting-App#9]
- [x] User deletion
- [x] MenuMain team leaderboard text
- [x] Button click animations
- [x] Install and setup instructions in readme file

- [x] Needs new Chrome to function

- [x] Router needs to give error while viewing a team that doesn't exist
- [x] Input next button should be greyed out until all inputs are filled

- [x] Change `<p>` to `<pre>` with other CSS
- [x] Reset array after saving scouting
